### PR TITLE
:bug: fix: Cannot read property 'range' of null

### LINKED ISSUE #31: Cannot read property 'range' of null
```
ERROR  Failed to compile with 1 errors3:43:32 PM

 error  in ./src/router/paths.js

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (D:\admx\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (D:\admx\node_modules\eslint\lib\rules\template-curly-spacing.js:52:42)
    at TemplateElement (D:\admx\node_modules\eslint\lib\rules\template-curly-spacing.js:117:17)
    at D:\admx\node_modules\eslint\lib\util\safe-emitter.js:47:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\admx\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (D:\admx\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\admx\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (D:\admx\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (D:\admx\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (D:\admx\node_modules\eslint\lib\linter.js:865:28)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:132:14)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (D:\admx\node_modules\eslint\lib\util\traverser.js:147:30)

 @ ./src/router/index.js 15:0-28 21:10-15
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.5:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

### PR DESCRIPTION
**Pull request by anselal**
Closes #31

### CODE REVIEW

**Comment by anselal** [comment]
@ClintOxx if you merge this could you tag this as `hacktoberfest-accepted` please ?

**Comment by ClintOxx** [comment]
@anselal Yea sure, thanks!

**Comment by anselal** [comment]
you need to label this PR as `hacktoberfest-accepted`
the repo can have a topic of `hacktoberfest`

**Comment by ClintOxx** [comment]
Gotcha, just added that label, couldn’t do it from the mobile app. 

I’ll check over the other requests and comments Friday or Saturday @anselal

**Pull request merged**
