### PR TITLE
Fixes #6

### LINKED ISSUE #6: Alert menu wrong position
Windows 10
Firefox 68.0.1

when clicking on the alert bell icon, the alert menu appears off-screen to the right instead of below the icon

### PR DESCRIPTION
**Pull request by MiKr13**
This update contains:
- Fix for #6 
- Linting of code
- Package update as npm/yarn install was failing. The packages are minor updates so there are no breaking changes

Main files where fix #6 is: App.vue, Drawer.vue, Footer.vue, Toolbar.vue, DashboardView.vue, LoginHome.vue

I'll suggest that changes be viewed with whitespace differences ignored.

### CODE REVIEW

**Comment by MiKr13** [comment]
I am following default markup provided in Vuetify docs: https://v15.vuetifyjs.com/en/framework/default-markup
The bug was happening because JS wasn't able to calculate the width of the body perfectly.

**Comment by anselal** [comment]
It would be better for you to create a pull request from a new branch and not your master branch.
For now just leave it that way, but keep in mind that is a good practice.
the reason is to keep your master clear, also It will be easier for you to update your fork later

**Comment by anselal** [comment]
which dashboard do you mean ?

**Comment by MiKr13** [comment]
@anselal I am talking about this newer one with Vuetify Version 2 and updated look & feel: [vuetify-masterial-dashboard](https://www.creative-tim.com/product/vuetify-material-dashboard?ref=vuetifyjs.com&partner=116160) so I don't bother much with this older version.

**Comment by anselal** [comment]
@ClintOxx template has more features than the original template from creative tim.
It implements tables, dark theme and a login page which is not available in the free version

**Comment by ClintOxx** [comment]
Thanks @MiKr13 @anselal

**Pull request merged**
